/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import personal.Profesor;
import school.university;
import java.util.Scanner;
import javax.swing.JOptionPane;
import school.Materia;
import menu.generarMateriasGrup;

/**
 *
 * @author ldrnt
 */
public class AdminMenu extends javax.swing.JFrame {
    private university uni;
    private Profesor profesor_vacio;
    private generarMateriasGrup generarmateriasGrup;
    private Materia materia;
    int control;
    /**
     * Creates new form AdminMenu
     */
    public AdminMenu(university uni, Profesor profesor_vacio) {
        this.uni = uni;
        this.profesor_vacio = profesor_vacio;
        this.generarmateriasGrup = new generarMateriasGrup(uni, profesor_vacio);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crearProfesor = new javax.swing.JButton();
        crearGrupo = new javax.swing.JButton();
        inscribirAlumno = new javax.swing.JButton();
        crearMateria = new javax.swing.JButton();
        listadoProfs = new javax.swing.JButton();
        listadoAlumnos = new javax.swing.JButton();
        listadoGrupos = new javax.swing.JButton();
        listadoMaterias = new javax.swing.JButton();
        backPrincipal1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setText("Menú del Administrador");

        crearProfesor.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        crearProfesor.setText("Crear un profesor");
        crearProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProfesorActionPerformed(evt);
            }
        });

        crearGrupo.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        crearGrupo.setText("Crear un grupo");
        crearGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearGrupoActionPerformed(evt);
            }
        });

        inscribirAlumno.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        inscribirAlumno.setText("Inscribir un alumno");
        inscribirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribirAlumnoActionPerformed(evt);
            }
        });

        crearMateria.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        crearMateria.setText("Crear una materia");
        crearMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMateriaActionPerformed(evt);
            }
        });

        listadoProfs.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        listadoProfs.setText("Ver listado de profesores");
        listadoProfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoProfsActionPerformed(evt);
            }
        });

        listadoAlumnos.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        listadoAlumnos.setText("Ver listado de alumnos");
        listadoAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoAlumnosActionPerformed(evt);
            }
        });

        listadoGrupos.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        listadoGrupos.setText("Ver listado de grupos");
        listadoGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoGruposActionPerformed(evt);
            }
        });

        listadoMaterias.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        listadoMaterias.setText("Ver listado de materias");
        listadoMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoMateriasActionPerformed(evt);
            }
        });

        backPrincipal1.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        backPrincipal1.setText("Regresar");
        backPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPrincipal1ActionPerformed(evt);
            }
        });

        jButton1.setFont(crearProfesor.getFont());
        jButton1.setText("Crear un profesor Auxiliar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(backPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inscribirAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crearMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addComponent(crearProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crearGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listadoProfs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listadoAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listadoGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listadoMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearProfesor)
                    .addComponent(listadoProfs))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearGrupo)
                    .addComponent(listadoAlumnos))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscribirAlumno)
                    .addComponent(listadoGrupos))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearMateria)
                    .addComponent(listadoMaterias))
                .addGap(18, 18, 18)
                .addComponent(backPrincipal1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void crearProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProfesorActionPerformed
        crearProfe crearprofe = new crearProfe(null, uni,materia,control);
        crearprofe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearProfesorActionPerformed

    private void crearGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearGrupoActionPerformed
        if (uni == null || /*profesor_vacio == null ||*/generarmateriasGrup == null) {
        JOptionPane.showMessageDialog(this,
            "No se puede crear un grupo porque hay datos faltantes. " + (uni == null ? "uni" : "") + (profesor_vacio == null ? "profesor_vacio" : "") + (generarmateriasGrup == null ? "generarmateriasGrup" : ""),
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if(profesor_vacio == null){
            profesor_vacio = new Profesor();
        }
        crearGrupo creargrupo = new crearGrupo(uni, profesor_vacio, generarmateriasGrup);
        creargrupo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearGrupoActionPerformed

    private void inscribirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirAlumnoActionPerformed
        crearAlumno crearalumno = new crearAlumno(uni);
        crearalumno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inscribirAlumnoActionPerformed

    private void crearMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMateriaActionPerformed
        Menu.crear_materia(uni);
    }//GEN-LAST:event_crearMateriaActionPerformed

    private void listadoProfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoProfsActionPerformed
        JOptionPane.showMessageDialog(this, "----Listado de profesores----\n" + uni.imprimirProfesores());
    }//GEN-LAST:event_listadoProfsActionPerformed

    private void listadoAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoAlumnosActionPerformed
        JOptionPane.showMessageDialog(this, "----Listado de alummnos----\n" + uni.imprimirAlumnos());
    }//GEN-LAST:event_listadoAlumnosActionPerformed

    private void listadoGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoGruposActionPerformed
        JOptionPane.showMessageDialog(this, "----Listado de grupos----\n" + uni.imprimirGrupos());
    }//GEN-LAST:event_listadoGruposActionPerformed

    private void listadoMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoMateriasActionPerformed
        JOptionPane.showMessageDialog(this, "----Listado de materias----\n" + uni.imprimirMaterias());
    }//GEN-LAST:event_listadoMateriasActionPerformed

    private void backPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPrincipal1ActionPerformed
        PrincipalMenu principalMenu = new PrincipalMenu(uni, profesor_vacio);
        principalMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backPrincipal1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crearProfeAux crearprofeaux = new crearProfeAux(uni,materia,control);
        crearprofeaux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        university uni = new university();
        Profesor profesor_vacio = new Profesor();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu(uni, profesor_vacio).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backPrincipal1;
    private javax.swing.JButton crearGrupo;
    private javax.swing.JButton crearMateria;
    private javax.swing.JButton crearProfesor;
    private javax.swing.JButton inscribirAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listadoAlumnos;
    private javax.swing.JButton listadoGrupos;
    private javax.swing.JButton listadoMaterias;
    private javax.swing.JButton listadoProfs;
    // End of variables declaration//GEN-END:variables
}
