/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import javax.swing.JOptionPane;
import personal.Profesor;
import personal.Profesor_aux;
import personal.Roles;
import school.university;

/**
 *
 * @author ldrnt
 */
public class AlumnoMenu extends javax.swing.JFrame {
    private university uni;
    private Profesor profesor_vacio;
    /**
     * Creates new form AlumnoMenu
     */
    public AlumnoMenu(university uni, Profesor profesor_vacio) {
        this.uni = uni;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        verMateriasInscritas = new javax.swing.JButton();
        verCalif = new javax.swing.JButton();
        backPrincipalAlum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel1.setText("Menú Alumno");

        verMateriasInscritas.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        verMateriasInscritas.setText("Ver materias inscritas");
        verMateriasInscritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMateriasInscritasActionPerformed(evt);
            }
        });

        verCalif.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        verCalif.setText("Ver calificaciones");
        verCalif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCalifActionPerformed(evt);
            }
        });

        backPrincipalAlum.setFont(new java.awt.Font("Book Antiqua", 2, 14)); // NOI18N
        backPrincipalAlum.setText("Regresar");
        backPrincipalAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPrincipalAlumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(verMateriasInscritas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(verCalif)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backPrincipalAlum)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verMateriasInscritas)
                    .addComponent(verCalif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(backPrincipalAlum)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verMateriasInscritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMateriasInscritasActionPerformed
        String matricula = JOptionPane.showInputDialog("Dame la matricula del alumno:");
        if (uni.buscarAlumnoPorMatricula(matricula) != null) {
            JOptionPane.showMessageDialog(this, uni.buscarAlumnoPorMatricula(matricula).imprimirMaterias());
        } else {
            JOptionPane.showMessageDialog(this, "Alumno no encontrado","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_verMateriasInscritasActionPerformed

    private void verCalifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCalifActionPerformed
        String matricula = JOptionPane.showInputDialog("Dame la matricula del alumno:");
        if (uni.buscarAlumnoPorMatricula(matricula) != null) {
            JOptionPane.showMessageDialog(this, uni.buscarAlumnoPorMatricula(matricula).imprimirCalificaciones());
        } else {
            JOptionPane.showMessageDialog(this, "Alumno no encontrado","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_verCalifActionPerformed

    private void backPrincipalAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPrincipalAlumActionPerformed
        PrincipalMenu principalMenu = new PrincipalMenu(uni, profesor_vacio);
        principalMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backPrincipalAlumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        university uni = new university();
        Profesor profesor_vacio = new Profesor("","","","", Roles.PROFESOR, "","");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoMenu(uni, profesor_vacio).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backPrincipalAlum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton verCalif;
    private javax.swing.JButton verMateriasInscritas;
    // End of variables declaration//GEN-END:variables
}
