/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import personal.Profesor;
import personal.Roles;
import school.university;

/**
 *
 * @author ldrnt
 */
public class PrincipalMenu extends javax.swing.JFrame {
    private university uni;
    private Profesor profesor_vacio;
    private Menu menu;
    /**
     * Creates new form PrincipalMenu
     */
    public PrincipalMenu(university uni, Profesor profesor_vacio) {
        this.uni = uni;
        this.profesor_vacio = profesor_vacio;
        this.menu = new Menu();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        profesorButton = new javax.swing.JButton();
        alumnoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel1.setText("Menú Principal");

        adminButton.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        adminButton.setText("ADMINISTRADOR");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        profesorButton.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        profesorButton.setText("PROFESOR");
        profesorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesorButtonActionPerformed(evt);
            }
        });

        alumnoButton.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        alumnoButton.setText("ALUMNO");
        alumnoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profesorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alumnoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(adminButton)
                .addGap(45, 45, 45)
                .addComponent(profesorButton)
                .addGap(50, 50, 50)
                .addComponent(alumnoButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        AdminMenu adminMenu = new AdminMenu(uni, profesor_vacio);
        adminMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminButtonActionPerformed

    private void alumnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoButtonActionPerformed
        AlumnoMenu alumnoMenu = new AlumnoMenu(uni, profesor_vacio);
        alumnoMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alumnoButtonActionPerformed

    private void profesorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesorButtonActionPerformed
        ProfeMenu profeMenu = new ProfeMenu(uni, profesor_vacio);
        profeMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profesorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        university uni = new university();
        Profesor profesor_vacio = new Profesor("","","","", Roles.PROFESOR, "","");
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalMenu(uni, profesor_vacio).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton alumnoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton profesorButton;
    // End of variables declaration//GEN-END:variables
}
